server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/app?sslMode=REQUIRED&enabledTLSProtocols=TLSv1.2}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
management:
  endpoints:
    web.exposure.include: "health,info"
  endpoint.health.probes.enabled: true
