spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/app?sslMode=REQUIRED&enabledTLSProtocols=TLSv1.2}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web.exposure.include: "health,info"
  endpoint.health.probes.enabled: true
